SELECT C.CARTON_ID, (C.LEN*C.WIDTH*C.HEIGHT) as VOLUME 
FROM ORDERS.CARTON C
WHERE (C.LEN*C.WIDTH*C.HEIGHT) >= ( SELECT
SUM(P.LEN*P.WIDTH*P.HEIGHT*PRODUCT_QUANTITY) AS VOLUME
FROM ORDERS.ORDER_HEADER ORH
INNER JOIN ORDERS.ORDER_ITEMS ORI ON ORH.ORDER_ID = ORI.ORDER_ID
INNER JOIN ORDERS.PRODUCT P ON ORI.PRODUCT_ID =
P.PRODUCT_ID 
WHERE ORH.ORDER_ID =10006 
)
ORDER BY (C.LEN*C.WIDTH*C.HEIGHT) ASC
LIMIT 1 ;

--------------------------------------------------------------------------------------------------------------------------------

SELECT C.CUSTOMER_ID, C.CUSTOMER_FULLNAME, PRO.PRODUCT_QUANTITY, ORH.ORDER_ID 
FROM 
(
SELECT ORDER_ID, PRODUCT_QUANTITY FROM ORDERS.ORDER_ITEMS
GROUP BY ORDER_ID
HAVING SUM(PRODUCT_QUANTITY) > 10
) PRO 
INNER JOIN ORDERS.ORDER_HEADER ORH ON PRO.ORDER_ID = ORH.ORDER_ID AND 
ORH.ORDER_STATUS = 'SHIPPED'
INNER JOIN 
(
SELECT DISTINCT CUSTOMER_ID, 
CONCAT(CUSTOMER_FNAME,' ',CUSTOMER_LNAME) AS CUSTOMER_FULLNAME FROM 
ORDERS.ONLINE_CUSTOMER
) C ON ORH.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY C.CUSTOMER_ID;

-----------------------------------------------------------------------------------------------------------------------------------

SELECT ORI.ORDER_ID, OC.CUSTOMER_ID, CONCAT(OC.CUSTOMER_FNAME,' ',OC.CUSTOMER_LNAME) AS
CUSTOMER_NAME, ORI.TOTAL_QUANTITY
FROM ORDERS.ORDER_HEADER ORH 
INNER JOIN
(
SELECT ORDER_ID,
SUM(PRODUCT_QUANTITY) AS TOTAL_QUANTITY FROM ORDERS.ORDER_ITEMS 
GROUP BY ORDER_ID 
HAVING
ORDER_ID > 10060
) ORI
ON
ORH.ORDER_ID = ORI.ORDER_ID AND ORH.ORDER_STATUS = 'SHIPPED' 
INNER JOIN ORDERS.ONLINE_CUSTOMER OC ON ORH.CUSTOMER_ID = OC.CUSTOMER_ID;

-----------------------------------------------------------------------------------------------------------------------------------

SELECT PRO.PRODUCT_CLASS_DESC, SUM(PRO.PRODUCT_QUANTITY) PRODUCT_QUANTITY,
SUM(PRO.TOTAL_VALUE) TOTAL_VALUE, PRO.PRODUCT_CLASS_CODE
FROM
(
SELECT PC.PRODUCT_CLASS_DESC, ORI.PRODUCT_QUANTITY,
(ORI.PRODUCT_QUANTITY * P.PRODUCT_PRICE) TOTAL_VALUE, PC.PRODUCT_CLASS_CODE
FROM ORDERS.ORDER_ITEMS ORI
INNER JOIN ORDERS.ORDER_HEADER ORH ON ORH.ORDER_ID = ORI.ORDER_ID AND ORH.ORDER_STATUS = 'SHIPPED'
INNER JOIN ORDERS.ONLINE_CUSTOMER OC ON ORH.CUSTOMER_ID = OC.CUSTOMER_ID
INNER JOIN ORDERS.ADDRESS A ON OC.ADDRESS_ID = A.ADDRESS_ID AND A.COUNTRY NOT IN
('India','USA') 
LEFT JOIN ORDERS.PRODUCT P ON ORI.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN ORDERS.PRODUCT_CLASS PC ON P.PRODUCT_CLASS_CODE =
PC.PRODUCT_CLASS_CODE
) PRO
GROUP BY PRO.PRODUCT_CLASS_CODE, PRO.PRODUCT_CLASS_DESC
ORDER BY SUM(PRO.PRODUCT_QUANTITY) DESC
LIMIT 1;

----------------------------------------------------------------------------------------------------------------------------------
